name: Deploy to Salesforce Sandbox

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth-url.txt
          sfdx auth:sfdxurl:store -f auth-url.txt -a sfdev

      - name: Deploy to Sandbox
        run: |
          sfdx force:source:deploy -p force-app -u sfdev --testlevel RunLocalTests
