name: Deploy to Salesforce Sandbox

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Install Salesforce CLI (sf)
      run: npm install @salesforce/cli --global

    - name: Authenticate with SFDX URL
      run: |
        echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
        sf org login sfdx-url --sfdx-url-file auth.txt --alias sfdev --set-default

    - name: Confirm SFDX Project Directory
      run: |
        cd ci-cd-project
        ls
        cat sfdx-project.json

    - name: Deploy Metadata to Salesforce Sandbox
      run: |
        cd ci-cd-project
        sf project deploy start --source-dir force-app --target-org sfdev --test-level RunLocalTests --verbose
